# Generated by Django 4.2 on 2023-05-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('', 'Select User Type'), ('student', 'Student'), (
                'teacher', 'Teacher'), ('admin', 'Admin')], max_length=10),
        ),
    ]
