# Generated by Django 4.1.7 on 2023-05-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_user_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
