# Generated by Django 4.2 on 2023-05-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_studentrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('roll_num', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=50)),
                ('faculty', models.CharField(max_length=50)),
                ('sem', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ststus', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=30)),
            ],
        ),
    ]
