# Generated by Django 4.2 on 2023-06-01 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_user_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='user_id',
            new_name='username',
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
