# Generated by Django 4.2 on 2023-06-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_user_id_attendance_username_attendance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='usertype',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
