# Generated by Django 4.2 on 2023-05-11 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_attendance_time_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrecord',
            name='user_id',
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
