# Generated by Django 4.2 on 2023-05-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_studentrecord_user_id_studentrecord_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrecord',
            name='user',
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='user_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
