# Generated by Django 4.2 on 2023-06-01 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_attendance_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
    ]
