# Generated by Django 4.2 on 2023-06-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_attendance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roll_num',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
